-- Patch RA3 devices into the HomeWorks QS ProductMasterList (SQLREFERENCEINFO)
--
-- Problem: Even with SQLMODELINFO LinkType patches, Designer won't show RA3
-- devices in HW projects because the SQLREFERENCEINFO ProductMasterList for
-- HomeWorks QS (ProductInfoID=4) doesn't include RRD/RRDE ModelInfoIDs.
--
-- The ProductMasterList is THE gate that controls:
-- 1. Which devices appear in the HW project toolbox
-- 2. Which DeviceClass values are "supported" (IsDeviceClassSupported)
-- 3. Without this, device heard shows "device type not supported"
--
-- Fix: Add all RA3 CCA device ModelInfoIDs from the RadioRA2/3 product list
-- (ProductInfoID=3) into the HW product list (ProductInfoID=4).
--
-- Database chain:
--   TBLPRODUCTINFO (ProductInfoID=4 "HomeWorks QS")
--   → TBLPRODUCTINFOMODELINFOLIST (ID=5, type=3 "ProductMasterList")
--   → TBLPRODUCTINFOMODELINFOLISTCAT (ID=18 "Null Parent")
--   → TBLPRODINFOMDLINFOLISTMDLINFOID (ModelInfoIDs)
--
-- Run against: SQLREFERENCEINFO database on Designer VM
-- Requires: SQLMODELINFO accessible for cross-db join
--
-- IMPORTANT: Must also apply patch-ra3-to-hw-linktypes.sql on SQLMODELINFO
-- IMPORTANT: Restart Designer after applying (reference data is cached)

SET NOCOUNT ON;

-- RA3 product list categories (ProductInfoID=3 → PRODUCTINFOMODELINFOLISTID=4)
-- Categories: 7,8,9,10,11,12,13,14,15,17,19,23,26,27

DECLARE @hw_cat INT = 18;  -- HW ProductMasterList category
DECLARE @base INT = (SELECT ISNULL(MAX(SORTORDER), 0) FROM TBLPRODINFOMDLINFOLISTMDLINFOID WHERE PRODUCTINFOMODELINFOLISTCATID = @hw_cat);

-- Add RRD models
INSERT INTO TBLPRODINFOMDLINFOLISTMDLINFOID (PRODUCTINFOMODELINFOLISTCATID, MODELINFOID, SORTORDER, ISOBSOLETE, OVERRIDEFILTERINFOID)
SELECT @hw_cat, r.MODELINFOID, @base + ROW_NUMBER() OVER (ORDER BY r.MODELINFOID), 0, NULL
FROM (
  SELECT DISTINCT MODELINFOID
  FROM TBLPRODINFOMDLINFOLISTMDLINFOID
  WHERE PRODUCTINFOMODELINFOLISTCATID IN (7,8,9,10,11,12,13,14,15,17,19,23,26,27)
  AND MODELINFOID IN (
    SELECT m.MODELINFOID FROM [SQLMODELINFO].dbo.TBLMODELINFO m
    WHERE m.LUTRONMODELNUMBERBASE LIKE 'RRD%'
  )
) r
WHERE r.MODELINFOID NOT IN (
  SELECT MODELINFOID FROM TBLPRODINFOMDLINFOLISTMDLINFOID WHERE PRODUCTINFOMODELINFOLISTCATID = @hw_cat
);

PRINT 'Added RRD models: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';

-- Add RRDE and RRT models
SET @base = (SELECT ISNULL(MAX(SORTORDER), 0) FROM TBLPRODINFOMDLINFOLISTMDLINFOID WHERE PRODUCTINFOMODELINFOLISTCATID = @hw_cat);

INSERT INTO TBLPRODINFOMDLINFOLISTMDLINFOID (PRODUCTINFOMODELINFOLISTCATID, MODELINFOID, SORTORDER, ISOBSOLETE, OVERRIDEFILTERINFOID)
SELECT @hw_cat, r.MODELINFOID, @base + ROW_NUMBER() OVER (ORDER BY r.MODELINFOID), 0, NULL
FROM (
  SELECT DISTINCT MODELINFOID
  FROM TBLPRODINFOMDLINFOLISTMDLINFOID
  WHERE PRODUCTINFOMODELINFOLISTCATID IN (7,8,9,10,11,12,13,14,15,17,19,23,26,27)
  AND MODELINFOID IN (
    SELECT m.MODELINFOID FROM [SQLMODELINFO].dbo.TBLMODELINFO m
    WHERE m.LUTRONMODELNUMBERBASE LIKE 'RRDE%' OR m.LUTRONMODELNUMBERBASE LIKE 'RRT%'
  )
) r
WHERE r.MODELINFOID NOT IN (
  SELECT MODELINFOID FROM TBLPRODINFOMDLINFOLISTMDLINFOID WHERE PRODUCTINFOMODELINFOLISTCATID = @hw_cat
);

PRINT 'Added RRDE/RRT models: ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';

-- Verify
SELECT COUNT(*) AS total_ra3_in_hw_list
FROM TBLPRODINFOMDLINFOLISTMDLINFOID p
WHERE p.PRODUCTINFOMODELINFOLISTCATID = @hw_cat
AND p.MODELINFOID IN (
  SELECT m.MODELINFOID FROM [SQLMODELINFO].dbo.TBLMODELINFO m
  WHERE m.LUTRONMODELNUMBERBASE LIKE 'RRD%' OR m.LUTRONMODELNUMBERBASE LIKE 'RRDE%' OR m.LUTRONMODELNUMBERBASE LIKE 'RRT%'
);
