-- Patch RA3 (RadioRA 3) devices to be accepted in Homeworks QSX projects
--
-- Problem: Designer rejects RA3 CCA devices (RRD-*, RRDE-*, RRT-*, etc.)
-- during pairing in HW projects because their SQLMODELINFO entries only
-- list LinkType 9 (RadioRA 2) and 11 (HomeWorks Quantum), but NOT
-- LinkType 36 (HWQS GCU RF) which is what the HW processor's CCA link uses.
--
-- Cross-compatible devices like Picos (PJ2-*) already have all 5 link types:
--   9 (RadioRA 2), 11 (HomeWorks Quantum), 32 (MyRoom RF),
--   34 (MDU RF), 36 (HWQS GCU RF)
--
-- Fix: Add LinkTypes 32, 34, 36 to all RA3-only link nodes.
-- This is a database-only fix — no binary patching needed.
--
-- Run against: SQLMODELINFO database on Designer VM
--
-- Revert: Run patch-ra3-to-hw-linktypes-revert.sql
-- Or manually:
--   DELETE FROM TBLLINKNODEINFOLINKTYPEMAP
--   WHERE LINKTYPEID IN (32,34,36)
--   AND LINKNODEINFOID IN (
--     SELECT a.LINKNODEINFOID FROM TBLLINKNODEINFOLINKTYPEMAP a
--     WHERE a.LINKTYPEID = 9
--   );

SET NOCOUNT ON;

-- Add LinkType 32 (MyRoom RF) to all link nodes that have RadioRA 2 (9) but not HWQS GCU RF (36)
INSERT INTO TBLLINKNODEINFOLINKTYPEMAP (LINKNODEINFOID, LINKTYPEID, SORTORDER)
SELECT a.LINKNODEINFOID, 32, 1
FROM TBLLINKNODEINFOLINKTYPEMAP a
WHERE a.LINKTYPEID = 9
AND NOT EXISTS (SELECT 1 FROM TBLLINKNODEINFOLINKTYPEMAP b WHERE b.LINKNODEINFOID = a.LINKNODEINFOID AND b.LINKTYPEID = 32)
AND NOT EXISTS (SELECT 1 FROM TBLLINKNODEINFOLINKTYPEMAP c WHERE c.LINKNODEINFOID = a.LINKNODEINFOID AND c.LINKTYPEID = 36);

PRINT 'Added LinkType 32 (MyRoom RF): ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';

-- Add LinkType 34 (MDU RF)
INSERT INTO TBLLINKNODEINFOLINKTYPEMAP (LINKNODEINFOID, LINKTYPEID, SORTORDER)
SELECT a.LINKNODEINFOID, 34, 1
FROM TBLLINKNODEINFOLINKTYPEMAP a
WHERE a.LINKTYPEID = 9
AND NOT EXISTS (SELECT 1 FROM TBLLINKNODEINFOLINKTYPEMAP b WHERE b.LINKNODEINFOID = a.LINKNODEINFOID AND b.LINKTYPEID = 34)
AND NOT EXISTS (SELECT 1 FROM TBLLINKNODEINFOLINKTYPEMAP c WHERE c.LINKNODEINFOID = a.LINKNODEINFOID AND c.LINKTYPEID = 36);

PRINT 'Added LinkType 34 (MDU RF): ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';

-- Add LinkType 36 (HWQS GCU RF)
INSERT INTO TBLLINKNODEINFOLINKTYPEMAP (LINKNODEINFOID, LINKTYPEID, SORTORDER)
SELECT a.LINKNODEINFOID, 36, 1
FROM TBLLINKNODEINFOLINKTYPEMAP a
WHERE a.LINKTYPEID = 9
AND NOT EXISTS (SELECT 1 FROM TBLLINKNODEINFOLINKTYPEMAP b WHERE b.LINKNODEINFOID = a.LINKNODEINFOID AND b.LINKTYPEID = 36);

PRINT 'Added LinkType 36 (HWQS GCU RF): ' + CAST(@@ROWCOUNT AS VARCHAR) + ' rows';

-- Verify: show RRD-3LD link types after patch
SELECT m.LUTRONMODELNUMBERBASE, lt.LINKTYPEID, lt.DESCRIPTION as LinkType
FROM TBLMODELINFO m
JOIN TBLLINKNODEINFOMODELINFOMAP lnm ON lnm.MODELINFOID = m.MODELINFOID
JOIN TBLLINKNODEINFOLINKTYPEMAP ltm ON ltm.LINKNODEINFOID = lnm.LINKNODEINFOID
JOIN LSTLINKTYPE lt ON lt.LINKTYPEID = ltm.LINKTYPEID
WHERE m.LUTRONMODELNUMBERBASE = 'RRD-3LD'
ORDER BY lt.LINKTYPEID;

-- Verify: count remaining RA3-only nodes (should be 0)
SELECT COUNT(*) as RemainingRA3Only
FROM TBLLINKNODEINFOLINKTYPEMAP a
WHERE a.LINKTYPEID = 9
AND NOT EXISTS (SELECT 1 FROM TBLLINKNODEINFOLINKTYPEMAP b WHERE b.LINKNODEINFOID = a.LINKNODEINFOID AND b.LINKTYPEID = 36);
