/**
 * CCA - Lutron Clear Connect Type A Protocol Library
 *
 * This header is auto-generated by cbindgen. Do not edit manually.
 *
 * Usage:
 *   #include "cca.h"
 *
 *   CcaDecoder *decoder = cca_decoder_new();
 *   CcaPacket packet;
 *   if (cca_parse_bytes(decoder, data, len, &packet)) {
 *       printf("Device: %08X, Type: %s\n",
 *              packet.device_id,
 *              cca_packet_type_name(packet.packet_type));
 *   }
 *   cca_decoder_free(decoder);
 */


#ifndef CCA_H
#define CCA_H

/* Generated with cbindgen:0.26.0 */

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * CRC-16 polynomial used by Lutron (non-standard)
 */
#define CRC_POLY 51727

/**
 * Standard packet sizes
 */
#define PKT_STANDARD_LEN 24

#define PKT_PAIRING_LEN 53

#define TYPE 0

#define SEQUENCE 1

#define DEVICE_ID 2

#define FORMAT 7

#define BUTTON 10

#define ACTION 11

#define LEVEL 11

#define CRC_24 22

#define CRC_53 51

/**
 * Maximum raw packet size (pairing packets are 53 bytes)
 */
#define CCA_MAX_PACKET_LEN 56

/**
 * RF frequency in Hz
 */
#define FREQUENCY_HZ 433602844

/**
 * Baud rate
 */
#define BAUD_RATE 62484.7

/**
 * FSK deviation in Hz
 */
#define DEVIATION_HZ 41200

/**
 * Sync byte
 */
#define SYNC_BYTE 255

/**
 * Preamble bits
 */
#define PREAMBLE_BITS 32

/**
 * Sequence number increment
 */
#define SEQUENCE_INCREMENT 6

/**
 * Sequence wrap value
 */
#define SEQUENCE_WRAP 72

/**
 * Opaque decoder handle
 */
typedef struct CcaDecoder CcaDecoder;

/**
 * C-compatible decoded packet structure
 */
typedef struct CcaPacket {
    /**
     * Whether the packet is valid
     */
    bool valid;
    /**
     * Packet type byte (original wire value)
     */
    uint8_t packet_type;
    /**
     * Decoded packet type (may differ from wire if reclassified)
     */
    uint8_t decoded_type;
    /**
     * Sequence number
     */
    uint8_t sequence;
    /**
     * Source device ID (32-bit)
     */
    uint32_t device_id;
    /**
     * Target device ID (for bridge commands)
     */
    uint32_t target_id;
    /**
     * Button code (for button packets)
     */
    uint8_t button;
    /**
     * Action code (0=press, 1=release)
     */
    uint8_t action;
    /**
     * Level (0-100 for level/state packets)
     */
    uint8_t level;
    /**
     * Format byte at offset 7
     */
    uint8_t format_byte;
    /**
     * CRC value from packet
     */
    uint16_t crc;
    /**
     * Whether CRC is valid
     */
    bool crc_valid;
    /**
     * Raw packet bytes
     */
    uint8_t raw[CCA_MAX_PACKET_LEN];
    /**
     * Length of raw bytes
     */
    uintptr_t raw_len;
} CcaPacket;

extern void *malloc(uintptr_t size);

extern void free(void *ptr);

/**
 * Create a new CCA decoder instance
 *
 * Returns a pointer to the decoder, or NULL on failure.
 * The caller is responsible for calling `cca_decoder_free` to release memory.
 */
struct CcaDecoder *cca_decoder_new(void);

/**
 * Free a CCA decoder instance
 *
 * # Safety
 * The decoder pointer must be valid and not already freed.
 */
void cca_decoder_free(struct CcaDecoder *decoder);

/**
 * Decode raw CC1101 FIFO data to a Lutron packet
 *
 * This function handles N81 decoding from the raw bitstream.
 *
 * # Arguments
 * * `decoder` - Decoder instance
 * * `fifo_data` - Raw bytes from CC1101 RXFIFO
 * * `len` - Number of bytes
 * * `packet` - Output packet structure
 *
 * # Returns
 * `true` if a valid packet was decoded
 *
 * # Safety
 * All pointers must be valid and non-null.
 */
bool cca_decode_fifo(const struct CcaDecoder *decoder,
                     const uint8_t *fifo_data,
                     uintptr_t len,
                     struct CcaPacket *packet);

/**
 * Parse already-decoded packet bytes (skip N81 decoding)
 *
 * Use this when you have raw packet bytes that are already N81-decoded.
 *
 * # Arguments
 * * `decoder` - Decoder instance
 * * `bytes` - Decoded packet bytes (24-53 bytes)
 * * `len` - Number of bytes
 * * `packet` - Output packet structure
 *
 * # Returns
 * `true` if valid packet structure
 *
 * # Safety
 * All pointers must be valid and non-null.
 */
bool cca_parse_bytes(const struct CcaDecoder *decoder,
                     const uint8_t *bytes,
                     uintptr_t len,
                     struct CcaPacket *packet);

/**
 * Calculate CRC-16 for packet data
 *
 * # Arguments
 * * `data` - Bytes to calculate CRC over
 * * `len` - Number of bytes
 *
 * # Returns
 * 16-bit CRC value
 */
uint16_t cca_calc_crc(const uint8_t *data, uintptr_t len);

/**
 * Verify CRC of a complete packet
 *
 * # Arguments
 * * `packet` - Complete packet including CRC
 * * `len` - Packet length (24 for standard, 53 for pairing)
 *
 * # Returns
 * `true` if CRC is valid
 */
bool cca_verify_crc(const uint8_t *packet, uintptr_t len);

/**
 * Decode a single N81 byte from bitstream
 *
 * # Arguments
 * * `bits` - Packed bit data (MSB-first byte order)
 * * `bit_offset` - Starting bit position
 * * `byte_out` - Output decoded byte
 *
 * # Returns
 * `true` if valid N81 framing
 */
bool cca_decode_n81_byte(const uint8_t *bits,
                         uintptr_t bits_len,
                         uintptr_t bit_offset,
                         uint8_t *byte_out);

/**
 * Get human-readable packet type name
 *
 * # Returns
 * Static string pointer (do not free)
 */
const char *cca_packet_type_name(uint8_t pkt_type);

/**
 * Get human-readable button name
 *
 * # Returns
 * Static string pointer (do not free)
 */
const char *cca_button_name(uint8_t button);

/**
 * Get expected packet length for a type byte
 *
 * # Returns
 * Expected length (24 or 53), or 0 for unknown types
 */
uintptr_t cca_get_packet_length(uint8_t type_byte);

/**
 * Format device ID as hex string
 *
 * # Arguments
 * * `device_id` - 32-bit device ID
 * * `buffer` - Output buffer (at least 9 bytes)
 * * `buffer_len` - Buffer size
 *
 * # Returns
 * Number of bytes written (excluding null terminator), or 0 on error
 */
uintptr_t cca_format_device_id(uint32_t device_id, char *buffer, uintptr_t buffer_len);

#endif /* CCA_H */
