#!/usr/bin/env npx tsx
/**
 * Validate packets generated by the blog post packet visualizer
 * against the actual protocol tooling.
 */

import { CRC, FRAMING, identifyPacket, LENGTHS, parseDeviceId, RF, SEQUENCE } from "../protocol/protocol-ui";

// CRC-16 with poly 0xCA0F (same implementation as rtlsdr-cca-decode.ts)
const CRC_TABLE: number[] = [];
for (let i = 0; i < 256; i++) {
  let crc = i << 8;
  for (let j = 0; j < 8; j++) {
    crc = (crc & 0x8000) ? ((crc << 1) ^ 0xCA0F) & 0xFFFF : (crc << 1) & 0xFFFF;
  }
  CRC_TABLE.push(crc);
}

function calcCrc(data: number[]): number {
  let crc = 0;
  for (const byte of data) {
    const upper = (crc >> 8) & 0xFF;
    crc = (((crc << 8) & 0xFF00) + byte) ^ CRC_TABLE[upper];
  }
  return crc & 0xFFFF;
}

// Build a packet the same way the visualizer does
function buildPacket(opts: {
  type: number;
  seq: number;
  devId: number[];
  format: number;
  picoFrame: number;
  button?: number;
  action?: number;
  broadcast9_13?: boolean;
  targetId?: number[];
  cmdClass?: number;
  cmdParam?: number;
}): number[] {
  const p = new Array(24).fill(0x00);
  p[0] = opts.type;
  p[1] = opts.seq;
  p[2] = opts.devId[0]; p[3] = opts.devId[1]; p[4] = opts.devId[2]; p[5] = opts.devId[3];
  p[6] = 0x21;
  p[7] = opts.format;
  p[8] = opts.picoFrame;

  if (opts.broadcast9_13) {
    p[9] = 0xFF; p[10] = 0xFF; p[11] = 0xFF; p[12] = 0xFF; p[13] = 0xFF;
    if (opts.targetId) {
      p[14] = opts.targetId[0]; p[15] = opts.targetId[1];
      p[16] = opts.targetId[2]; p[17] = opts.targetId[3];
    }
  } else {
    if (opts.button !== undefined) p[10] = opts.button;
    if (opts.action !== undefined) p[11] = opts.action;
    if (opts.format === 0x0E) {
      // extended: device_repeat at 12-15, cmd_class at 17, cmd_param at 19
      p[12] = opts.devId[0]; p[13] = opts.devId[1]; p[14] = opts.devId[2]; p[15] = opts.devId[3];
      if (opts.cmdClass !== undefined) p[17] = opts.cmdClass;
      if (opts.cmdParam !== undefined) p[19] = opts.cmdParam;
    }
  }

  const crc = calcCrc(p.slice(0, 22));
  p[22] = (crc >> 8) & 0xFF;
  p[23] = crc & 0xFF;
  return p;
}

// ── Tests ──────────────────────────────────────────────────────────────────

let pass = 0, fail = 0;
function check(label: string, condition: boolean, detail?: string) {
  if (condition) {
    console.log(`  ✓ ${label}`);
    pass++;
  } else {
    console.log(`  ✗ ${label}${detail ? ' — ' + detail : ''}`);
    fail++;
  }
}

// 1. Validate protocol constants match what the visualizer uses
console.log("\n=== Protocol constants ===");
check("CRC poly = 0xCA0F", CRC.POLYNOMIAL === 0xCA0F, `got 0x${CRC.POLYNOMIAL.toString(16)}`);
check("Sync byte = 0xFF", FRAMING.SYNC_BYTE === 0xFF, `got 0x${FRAMING.SYNC_BYTE.toString(16)}`);
check("FADE prefix = [0xFA, 0xDE]", FRAMING.PREFIX[0] === 0xFA && FRAMING.PREFIX[1] === 0xDE);
check("Preamble = 0xAAAAAAAA", FRAMING.PREAMBLE_PATTERN === 0xAAAAAAAA);
check("Freq = 433602844 Hz", RF.FREQUENCY_HZ === 433602844);
check("Seq increment = 6", SEQUENCE.INCREMENT === 6);
check("Seq wrap = 0x48", SEQUENCE.WRAP === 0x48);
check("Standard length = 24", LENGTHS.STANDARD === 24);

// 2. Validate CRC calculation matches decoder
console.log("\n=== CRC calculation ===");
const testPayload = [0x88, 0x06, 0x12, 0x34, 0x56, 0x78, 0x21, 0x04, 0x03, 0x00, 0x02, 0x00, 0,0,0,0,0,0,0,0,0,0];
const crc = calcCrc(testPayload);
check("CRC is 16-bit", crc >= 0 && crc <= 0xFFFF, `got ${crc}`);
check("CRC is non-zero for real data", crc !== 0, `got 0x${crc.toString(16)}`);
// Verify CRC validates (recalc over full 24 bytes should give 0 if appended correctly... actually CRC-16 w/ this algo doesn't necessarily do that)
// Instead just verify round-trip: build packet, extract CRC, recalc, compare
const fullPkt = buildPacket({ type: 0x88, seq: 0x06, devId: [0x12,0x34,0x56,0x78], format: 0x04, picoFrame: 0x03, button: 0x02, action: 0x00 });
const extractedCrc = (fullPkt[22] << 8) | fullPkt[23];
const recalcCrc = calcCrc(fullPkt.slice(0, 22));
check("CRC round-trip matches", extractedCrc === recalcCrc, `extracted=0x${extractedCrc.toString(16)} recalc=0x${recalcCrc.toString(16)}`);

// 3. Validate each visualizer preset through identifyPacket
console.log("\n=== Preset: ON press (TAP format 0x04) ===");
{
  const pkt = buildPacket({ type: 0x88, seq: 0x06, devId: [0x12,0x34,0x56,0x78], format: 0x04, picoFrame: 0x03, button: 0x02, action: 0x00 });
  check("Length = 24", pkt.length === 24);
  const id = identifyPacket(pkt);
  check(`Type resolves (got "${id.typeName}")`, id.category === "BUTTON", `category=${id.category}`);
  check("Protocol byte = 0x21", pkt[6] === 0x21);
  check("Format byte = 0x04", pkt[7] === 0x04);
  check("Button byte = 0x02 (ON)", pkt[10] === 0x02);
  check("Action byte = 0x00 (PRESS)", pkt[11] === 0x00);
  const hexBytes = pkt.map(b => b.toString(16).padStart(2, '0'));
  check("Device ID parses BE", parseDeviceId(hexBytes, 2, "big") === "12345678");
  console.log(`  Hex: ${hexBytes.join(' ').toUpperCase()}`);
}

console.log("\n=== Preset: RAISE hold (HOLD format 0x0C) ===");
{
  const pkt = buildPacket({ type: 0x88, seq: 0x06, devId: [0x12,0x34,0x56,0x78], format: 0x0C, picoFrame: 0x03, button: 0x05, action: 0x02 });
  const id = identifyPacket(pkt);
  check(`Identified as PICO_HOLD (got "${id.typeName}")`, id.typeName === "PICO_HOLD");
  check("Is virtual type", id.isVirtual === true);
  check("Button = 0x05 (RAISE)", pkt[10] === 0x05);
  check("Action = 0x02 (HOLD)", pkt[11] === 0x02);
  console.log(`  Hex: ${pkt.map(b => b.toString(16).padStart(2, '0')).join(' ').toUpperCase()}`);
}

console.log("\n=== Preset: LOWER release (TAP format 0x04) ===");
{
  const pkt = buildPacket({ type: 0x88, seq: 0x06, devId: [0x12,0x34,0x56,0x78], format: 0x04, picoFrame: 0x03, button: 0x06, action: 0x01 });
  const id = identifyPacket(pkt);
  check(`Type resolves (got "${id.typeName}")`, id.category === "BUTTON");
  check("Button = 0x06 (LOWER)", pkt[10] === 0x06);
  check("Action = 0x01 (RELEASE)", pkt[11] === 0x01);
  console.log(`  Hex: ${pkt.map(b => b.toString(16).padStart(2, '0')).join(' ').toUpperCase()}`);
}

console.log("\n=== Preset: Scene save (EXT format 0x0E) ===");
{
  const pkt = buildPacket({ type: 0x89, seq: 0x06, devId: [0xAB,0xCD,0xEF,0x01], format: 0x0E, picoFrame: 0x03, button: 0x0B, action: 0x03, cmdClass: 0x09, cmdParam: 0x00 });
  const id = identifyPacket(pkt);
  check(`Identified as PICO_EXTENDED (got "${id.typeName}")`, id.typeName === "PICO_EXTENDED");
  check("Is virtual type", id.isVirtual === true);
  check("Button = 0x0B (SCENE1)", pkt[10] === 0x0B);
  check("Action = 0x03 (SAVE)", pkt[11] === 0x03);
  check("Device repeat matches source", pkt[12] === 0xAB && pkt[13] === 0xCD && pkt[14] === 0xEF && pkt[15] === 0x01);
  check("Cmd class = 0x09 (SCENE)", pkt[17] === 0x09);
  console.log(`  Hex: ${pkt.map(b => b.toString(16).padStart(2, '0')).join(' ').toUpperCase()}`);
}

console.log("\n=== Preset: Pico reset (format 0x0C + broadcast) ===");
{
  const pkt = buildPacket({ type: 0x88, seq: 0x06, devId: [0x12,0x34,0x56,0x78], format: 0x0C, picoFrame: 0x03, broadcast9_13: true, targetId: [0x12,0x34,0x56,0x78] });
  const id = identifyPacket(pkt);
  check(`Identified as PICO_RESET (got "${id.typeName}")`, id.typeName === "PICO_RESET");
  check("Is virtual type", id.isVirtual === true);
  check("Bytes 9-13 = FF FF FF FF FF", pkt[9] === 0xFF && pkt[10] === 0xFF && pkt[11] === 0xFF && pkt[12] === 0xFF && pkt[13] === 0xFF);
  check("Target ID at 14-17", pkt[14] === 0x12 && pkt[15] === 0x34 && pkt[16] === 0x56 && pkt[17] === 0x78);
  console.log(`  Hex: ${pkt.map(b => b.toString(16).padStart(2, '0')).join(' ').toUpperCase()}`);
}

// Summary
console.log(`\n${'='.repeat(40)}`);
console.log(`${pass} passed, ${fail} failed`);
if (fail > 0) process.exit(1);
